services:
  - type: web
    name: speed-car-wash-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: ${TELEGRAM_TOKEN}
      - key: ADMIN_IDS
        value: ${ADMIN_IDS}
      - key: GROUP_ID
        value: ${GROUP_ID}