services:
  - type: worker
    name: speed-car-wash-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app/bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: ${TELEGRAM_BOT_TOKEN}
      - key: ADMIN_IDS
        value: ${ADMIN_IDS}
      - key: GROUP_ID
        value: ${GROUP_ID}
